sudo: false
cache:
  directories:
    - "$HOME"
language: python
python:
    - 2.7.8
    - 2.7
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requirements.txt ; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install coveralls ; fi
script:
  - python setup.py test
  - coverage run --source=src setup.py test
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: never
